CREATE TABLE PERSON_INFO(
PID NUMBER,
F_NAME VARCHAR2(50),
L_NAME VARCHAR2(50),
DOB DATE,
PHONE VARCHAR2(30),
EMAIL VARCHAR2(30),
ADDRESS VARCHAR2(225),
PROFESSION VARCHAR2(50),
ORGANIZATION VARCHAR2(100),
CONSTRAINTS PK_PERSON_INFO PRIMARY KEY(PID)
);

CREATE TABLE TRANSACTION_TYPE(
TT_ID NUMBER,
TT_TYPE VARCHAR2(20),
CONSTRAINTS PK_TRANSACTION_TYPE PRIMARY KEY(TT_ID)
); 

CREATE TABLE ACCOUNT_TYPE(
ACC_TYPE VARCHAR2(20),
AT_ID NUMBER,
CONSTRAINTS PK_ACCOUNT_TYPE PRIMARY KEY(AT_ID)
);

CREATE TABLE ACCOUNTS(
ACC_NO NUMBER(15),
CARD_NO NUMBER(12),
CARD_PIN NUMBER(4),
BALANCE NUMBER(9,2),
CREATION_DATE DATE,
ACC_TYPE NUMBER,
PID_OWNER NUMBER,
CONSTRAINTS PK_ACCOUNTS PRIMARY KEY (ACC_NO),
CONSTRAINTS FK_ACCOUNTS_TYPE FOREIGN KEY (ACC_TYPE) REFERENCING ACCOUNT_TYPE(AT_ID),
CONSTRAINTS FK_PERSON_ACCOUNT FOREIGN KEY (PID_OWNER) REFERENCING PERSON_INFO(PID),
CONSTRAINTS FK_PERSON_UNIQUE UNIQUE(PID_OWNER)
);

CREATE TABLE USERS(
USERNAME VARCHAR2(30),
PASSWORD VARCHAR2(100),
CREATION DATE,
USER_PID NUMBER,
USER_ACC_No NUMBER,
CONSTRAINTS PK_USERS PRIMARY KEY (USERNAME),
CONSTRAINTS FK_PERSON_USER FOREIGN KEY(USER_PID) REFERENCING PERSON_INFO(PID),
CONSTRAINTS FK_ACCOUNT_USER FOREIGN KEY (USER_ACC_No) REFERENCING ACCOUNTS(ACC_NO)
);

CREATE TABLE LOG_REPORT(
LOG_IN DATE,
LOG_OUT DATE,
LOG_ID NUMBER UNIQUE,
USER_ID VARCHAR2(30),
REPORT CLOB,
CONSTRAINTS FK_USER_LOG FOREIGN KEY (USER_ID) REFERENCING USERS(USERNAME)
);

CREATE TABLE TRANSACTIONS(
TID NUMBER,
FR_ACC NUMBER(15),
TO_ACC NUMBER(15),
TR_DATE DATE,
NARRATION VARCHAR2(255),
TR_TYPE NUMBER,
CONSTRAINTS PK_TRANS PRIMARY KEY (TID),
CONSTRAINTS FK_ACC_FR FOREIGN KEY (FR_ACC) REFERENCING ACCOUNTS(ACC_NO),
CONSTRAINTS FK_ACC_TO FOREIGN KEY (TO_ACC) REFERENCING ACCOUNTS(ACC_NO), 
CONSTRAINTS FK_TR_TYPE FOREIGN KEY (TR_TYPE) REFERENCING TRANSACTION_TYPE(TT_ID)
);

CREATE SEQUENCE SEQ_PERSON_INFO
START WITH 1
INCREMENT by 1
MINVALUE 0;

CREATE SEQUENCE SEQ_ACCOUNTS
START WITH 1
INCREMENT by 1
MINVALUE 0
MAXVALUE 9999
CYCLE;

CREATE SEQUENCE SEQ_TRANSACTIONS
START WITH 1
INCREMENT by 1
MINVALUE 0;

CREATE SEQUENCE SEQ_LOG_REPORT
START WITH 1
INCREMENT by 1
MINVALUE 0;



INSERT INTO TRANSACTION_TYPE(TT_ID,TT_TYPE) VALUES (1,'DEPOSIT');
INSERT INTO TRANSACTION_TYPE(TT_ID,TT_TYPE) VALUES (2,'WITHDRAW');
INSERT INTO TRANSACTION_TYPE(TT_ID,TT_TYPE) VALUES (3,'TRANSFER');
INSERT INTO TRANSACTION_TYPE(TT_ID,TT_TYPE) VALUES (4,'PAY BILL');


INSERT INTO ACCOUNT_TYPE(ACC_TYPE,AT_ID) VALUES('CURRENT ACCOUNT', 100);
INSERT INTO ACCOUNT_TYPE(ACC_TYPE,AT_ID) VALUES('SAVINGS ACCOUNT', 200);
INSERT INTO ACCOUNT_TYPE(ACC_TYPE,AT_ID) VALUES('STUDENT ACCOUNT', 300);
INSERT INTO ACCOUNT_TYPE(ACC_TYPE,AT_ID) VALUES('FC ACCOUNT',400);

INSERT INTO PERSON_INFO(PID,F_NAME,L_NAME,DOB,PHONE,EMAIL,ADDRESS,PROFESSION,ORGANIZATION) VALUES(SEQ_PERSON_INFO.nextval,'MODAH','RAFFA',SYSDATE,'01822712160','modah@gmail.com','GAZIPUR','DOCTOR','UNO');
INSERT INTO PERSON_INFO(PID,F_NAME,L_NAME,DOB,PHONE,EMAIL,ADDRESS,PROFESSION,ORGANIZATION) VALUES(SEQ_PERSON_INFO.nextval,'KIMBI','TREY',SYSDATE,'01820609876','kimbi@gmail.com','CHOURASTA','ENGINEER','NONE');
INSERT INTO PERSON_INFO(PID,F_NAME,L_NAME,DOB,PHONE,EMAIL,ADDRESS,PROFESSION,ORGANIZATION) VALUES(SEQ_PERSON_INFO.nextval,'ALASANE','TREY',SYSDATE,'01820600870','Alasanetrey@gmail.com','TONGI','ENGINEER','NONE');
INSERT INTO PERSON_INFO(PID,F_NAME,L_NAME,DOB,PHONE,EMAIL,ADDRESS,PROFESSION,ORGANIZATION) VALUES(SEQ_PERSON_INFO.nextval,'STEVO','TEEE',SYSDATE,'01800000000','stevoo_Tee@gmail.com','CHOURASTA','DOCTOR','UN0');
INSERT INTO PERSON_INFO(PID,F_NAME,L_NAME,DOB,PHONE,EMAIL,ADDRESS,PROFESSION,ORGANIZATION) VALUES(SEQ_PERSON_INFO.nextval,'ZEEEEE','MANIA',SYSDATE,'01820609876','zeee_mania@gmail.com','GAZIPUR','ENGINEER','NONE');
INSERT INTO PERSON_INFO(PID,F_NAME,L_NAME,DOB,PHONE,EMAIL,ADDRESS,PROFESSION,ORGANIZATION) VALUES(SEQ_PERSON_INFO.nextval,'MOUTONGON','MANI',SYSDATE,'01800008876','moutongon@gmail.com','CHOURASTA','PILOT','OIC');
INSERT INTO PERSON_INFO(PID,F_NAME,L_NAME,DOB,PHONE,EMAIL,ADDRESS,PROFESSION,ORGANIZATION) VALUES(SEQ_PERSON_INFO.nextval,'ZLATAN','KAI',SYSDATE,'01720609876','zlatankai@gmail.com','CHOURASTA','ENGINEER','NONE');
INSERT INTO PERSON_INFO(PID,F_NAME,L_NAME,DOB,PHONE,EMAIL,ADDRESS,PROFESSION,ORGANIZATION) VALUES(SEQ_PERSON_INFO.nextval,'LEO','MESSI',SYSDATE,'01830609876','leo_messi@gmail.com','TONGI','FOOTBALL','OIC');
INSERT INTO PERSON_INFO(PID,F_NAME,L_NAME,DOB,PHONE,EMAIL,ADDRESS,PROFESSION,ORGANIZATION) VALUES(SEQ_PERSON_INFO.nextval,'CRISTIANO','RONALDO',SYSDATE,'01670609876','cristianoronalado@gmail.com','CHOURASTA','FOOTBALL','NONE');
INSERT INTO PERSON_INFO(PID,F_NAME,L_NAME,DOB,PHONE,EMAIL,ADDRESS,PROFESSION,ORGANIZATION) VALUES(SEQ_PERSON_INFO.nextval,'MAXWELL','GIREMY',SYSDATE,'01980609876','maxwellgeremy@gmail.com','BASUNDHARA','ENGINEER','NONE');
INSERT INTO PERSON_INFO(PID,F_NAME,L_NAME,DOB,PHONE,EMAIL,ADDRESS,PROFESSION,ORGANIZATION) VALUES(SEQ_PERSON_INFO.nextval,'NICK','LARSON',SYSDATE,'01920609876','nickilarson@gmail.com','GAZIPUR','DETECTIVE','NONE');



INSERT INTO ACCOUNTS(ACC_NO,CARD_NO,CARD_PIN,BALANCE,CREATION_DATE,ACC_TYPE,PID_OWNER) VALUES(SEQ_ACCOUNTS.nextval,1000,0314,100000,SYSDATE,100,3);
INSERT INTO ACCOUNTS(ACC_NO,CARD_NO,CARD_PIN,BALANCE,CREATION_DATE,ACC_TYPE,PID_OWNER) VALUES(SEQ_ACCOUNTS.nextval,2000,7084,200000,SYSDATE,100,6);
INSERT INTO ACCOUNTS(ACC_NO,CARD_NO,CARD_PIN,BALANCE,CREATION_DATE,ACC_TYPE,PID_OWNER) VALUES(SEQ_ACCOUNTS.nextval,3000,9134,150000,SYSDATE,200,2);
INSERT INTO ACCOUNTS(ACC_NO,CARD_NO,CARD_PIN,BALANCE,CREATION_DATE,ACC_TYPE,PID_OWNER) VALUES(SEQ_ACCOUNTS.nextval,4000,2054,2500000,SYSDATE,400,10);
INSERT INTO ACCOUNTS(ACC_NO,CARD_NO,CARD_PIN,BALANCE,CREATION_DATE,ACC_TYPE,PID_OWNER) VALUES(SEQ_ACCOUNTS.nextval,5000,1004,90000000,SYSDATE,300,4);




INSERT INTO PERSON_INFO(PID,F_NAME,L_NAME,DOB,PHONE,EMAIL,ADDRESS,PROFESSION,ORGANIZATION) VALUES(SEQ_PERSON_INFO.nextval,'MAXWELL','GIREMY',SYSDATE,'01980609876','maxwellgeremy@gmail.com','BASUNDHARA','ENGINEER','NONE');
INSERT INTO ACCOUNTS(ACC_NO,CARD_NO,CARD_PIN,BALANCE,CREATION_DATE,ACC_TYPE,PID_OWNER) VALUES(SEQ_ACCOUNTS.nextval,1000,0314,5000,SYSDATE,100,3);
INSERT INTO USERS(USERNAME, PASSWORD, CREATION, USER_PID, USER_ACC_No) VALUES('MAXWELL','12345678',SYSDATE, 100, 15);


-------------------------------------------------------------------------------------------------------------------------
INSERT INTO PERSON_INFO(PID,F_NAME,L_NAME,DOB,PHONE,EMAIL,ADDRESS,PROFESSION,ORGANIZATION) VALUES(SEQ_PERSON_INFO.nextval,'PROF','SAD',SYSDATE,'0199999999','PROFSAGA@gmail.com','BASUNDHARA','TEACHER','NONE');
INSERT INTO ACCOUNTS(ACC_NO,CARD_NO,CARD_PIN,BALANCE,CREATION_DATE,ACC_TYPE,PID_OWNER) VALUES(SEQ_ACCOUNTS.nextval,1290,0994,100,SYSDATE,100,42);
INSERT INTO USERS(USERNAME, PASSWORD, CREATION, USER_PID, USER_ACC_No) VALUES('Prof','9876543210',SYSDATE, 42,42);


INSERT INTO PERSON_INFO(PID,F_NAME,L_NAME,DOB,PHONE,EMAIL,ADDRESS,PROFESSION,ORGANIZATION) VALUES(SEQ_PERSON_INFO.nextval,'ABOUBAKAR','MOUHAMMAD',SYSDATE,'0199999999','PROFSAGA@gmail.com','BASUNDHARA','TEACHER','NONE');
INSERT INTO ACCOUNTS(ACC_NO,CARD_NO,CARD_PIN,BALANCE,CREATION_DATE,ACC_TYPE,PID_OWNER) VALUES(SEQ_ACCOUNTS.nextval,2290,0995,10000,SYSDATE,100,43);
INSERT INTO USERS(USERNAME, PASSWORD, CREATION, USER_PID, USER_ACC_No) VALUES('ABOUBAKAR','X12345',SYSDATE, 43,43);

--------------------------------------------------------------------------------------------------------------------
INSERT INTO PERSON_INFO(PID,F_NAME,L_NAME,DOB,PHONE,EMAIL,ADDRESS,PROFESSION,ORGANIZATION) VALUES(SEQ_PERSON_INFO.nextval,'ABDOULAYE','MAMOUDOU',SYSDATE,'0128718902','AbdoulayeA@gmail.com','BASUNDHARA','DG','NONE');
INSERT INTO PERSON_INFO(PID,F_NAME,L_NAME,DOB,PHONE,EMAIL,ADDRESS,PROFESSION,ORGANIZATION) VALUES(SEQ_PERSON_INFO.nextval,'DAIROU','MOHAMAN',SYSDATE,'01822712167','dairou@gmail.com','BASUNDHARA','PRESIDENT','NONE');
INSERT INTO PERSON_INFO(PID,F_NAME,L_NAME,DOB,PHONE,EMAIL,ADDRESS,PROFESSION,ORGANIZATION) VALUES(SEQ_PERSON_INFO.nextval,'GUIDADO','OUMAR',SYSDATE,'01925225252','Oumar@gmail.com','BASUNDHARA','THUG','NONE');

INSERT INTO ACCOUNTS(ACC_NO,CARD_NO,CARD_PIN,BALANCE,CREATION_DATE,ACC_TYPE,PID_OWNER) VALUES(SEQ_ACCOUNTS.nextval,2390,0915,10000,SYSDATE,100,45);
INSERT INTO ACCOUNTS(ACC_NO,CARD_NO,CARD_PIN,BALANCE,CREATION_DATE,ACC_TYPE,PID_OWNER) VALUES(SEQ_ACCOUNTS.nextval,2490,0925,10000,SYSDATE,100,46);
INSERT INTO ACCOUNTS(ACC_NO,CARD_NO,CARD_PIN,BALANCE,CREATION_DATE,ACC_TYPE,PID_OWNER) VALUES(SEQ_ACCOUNTS.nextval,2590,1975,10000,SYSDATE,100,47);

INSERT INTO USERS(USERNAME, PASSWORD, CREATION, USER_PID, USER_ACC_No) VALUES('ABDOULAYE','abcdefgh',SYSDATE, 47,46);
INSERT INTO USERS(USERNAME, PASSWORD, CREATION, USER_PID, USER_ACC_No) VALUES('DAIROU','life_is_sweet',SYSDATE, 46,45);
INSERT INTO USERS(USERNAME, PASSWORD, CREATION, USER_PID, USER_ACC_No) VALUES('GUIDADO','GSW',SYSDATE, 45,44);


INSERT INTO LOG_REPORT(LOG_IN, LOG_OUT, LOG_ID, USER_ID, REPORT) VALUES(TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'), TO_DATE('2003/05/03 21:02:46', 'yyyy/mm/dd hh24:mi:ss'), SEQ_LOG_REPORT.nextval, 'GHOST', 'TRACK:: LOGIN -> WITHDRAW -> LOGOUT ->');
INSERT INTO LOG_REPORT(LOG_IN, LOG_OUT, LOG_ID, USER_ID, REPORT) VALUES(TO_DATE('2021/01/03 14:02:44', 'yyyy/mm/dd hh24:mi:ss'), TO_DATE('2003/05/03 20:02:46', 'yyyy/mm/dd hh24:mi:ss'), SEQ_LOG_REPORT.nextval, 'GHOST', 'TRACK:: LOGIN -> WITHDRAW -> LOGOUT ->');